services:
  mysql:
    image: mysql:8.0
    container_name: tmi-mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/db:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    environment:
      TZ: Asia/Seoul
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      timeout: 2s
    deploy:
      resources:
        limits:
          memory: 512m
    env_file:
      - ./backend/.env.prod

  backend:
    image: seongsiyeong/tmi-backend:latest
    container_name: tmi-backend
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Seoul
      JAVA_OPTS: "-Xms256m -Xmx256m"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./backend/.env.prod

  frontend:
    image: seongsiyeong/tmi-frontend:latest
    container_name: tmi-frontend
    environment:
      TZ: Asia/Seoul
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql-data:
